# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a727d63dcd73338a0f60ff88a71e26e02ef9784c0a9f59935d28d8d82d3cd431766f01beae7b8b472c40b80c40339fd6e61826a1bfe41628448c138ca90a4591

test:
  secret_key_base: b27bdc51977dd7ce7c7ef1102809ca3c7b356f99d89a4d2210b1ed1a4430d1c3c9c039576af630b408a527d77b75329558f9def67114f8b8bbd8c39554c94cd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
